
<div class="container footer">
    <p><?=  GVGCITATION  ?></p>  
    
    <div class="container reseaux">
		<a href="https://fr-fr.facebook.com/" target="_blank" title="S'ouvre dans un nouvel onglet vers la page Facebook"><img src="../public/icons/facebook.png" alt="iconFacebook" class="icons" /></a>
		<a href="https://twitter.com/" target="_blank" title="S'ouvre dans un nouvel onglet vers le fil Twitter"><img src="../public/icons/twitter.png" alt="iconTwitter" class="icons" /></a>
		<a href="https://vimeo.com/fr/" target="_blank" title="S'ouvre dans un nouvel onglet vers le compte Vimeo"><img src="../public/icons/vimeo.png" alt="iconVimeo" class="icons" /></a>
		<a href="https://www.instagram.com/?hl=fr" target="_blank" title="S'ouvre dans un nouvel onglet vers le compte Instagram"><img src="../public/icons/instagram.png" alt="iconInstagram" class="icons" /></a>
    </div>
    <div class="container footer end">
        <a href="#" title="About">About</a>
        <a href="#" title="Contact">Contact</a>
        <a href="#" title="CGU">CGU</a>
    </div>
</div>