
<h2>Modifier un Jeu Video dans la Base de données !</h2>


<div class="formRegister">
    <form action="index.php?road=updateGames" method="POST" onsubmit="return confirm('Voulez vous vraiment modifier ce jeu dans la base de données ?');">
        <input type="hidden" name="id" value="<?= $data['id'] ?>">
        
        <legend>Modification d'un Jeu Video :</legend>
        
        <?php require_once('_errors.phtml');?>
        <?php require_once('_valids.phtml');?>

        <label for="name">Entrez le nom</label>
        <input type="text" name="name" value="<?= $data['name'] ?>" size="30">
    
        <label for="descriptif">Descriptif du Jeu</label>
        <textarea type="textarea" name="descriptif" value="<?= $data['descriptif'] ?>" size="30"><?= $data['descriptif'] ?></textarea>
    
        <label for="multiplayerslocal">Multiplayers en local</label>
        <input type="text" name="multiplayerslocal" value="<?= $data['multiplayerslocal'] ?>" size="30">
    
        <label for="online">Y a t-il un mode online? si oui jusqu'à combien de joueurs peut-on jouer en ligne ?</label>
        <input type="text" name="online" value="<?= $data['online'] ?>" size="30">

        <label for="yearrelease">Année de Sortie du Jeu</label>
        <input type="number" name="yearrelease" value="<?= $data['yearrelease'] ?>" min="1990">
        
        <label for="price">Prix du jeu en euros</label>
        <input type="number" name="price" value="<?= $data['price'] ?>" max="180">
        
        <select name="category_id" class="category_id">
            <option value="vide">Category</option>
            <?php foreach($categoryOfGames as $category): ?>
                <option value="<?= htmlspecialchars($category['id']) ?>"><?= htmlspecialchars($category['category_game']) ?></option>
            <?php endforeach; ?>
        </select>

        <select name="pegi_id" class="pegi_id">
            <option value="vide">Age conseillé</option>
            <?php foreach($pegiAge as $pegi): ?>
                <option value="<?= htmlspecialchars($pegi['id']) ?>"><?= htmlspecialchars($pegi['pegi_age']) ?></option>
            <?php endforeach; ?>
        </select>
        
        <label for="image">Nom de l'image du Jeu</label>
        <input type="text" id="image" name="image" value="<?= $data['image'] ?>">
    
        <input type="submit" value="Valider"/>
    </form>
</div>