

<section>
    <h4>Espace BackOffice</h4>
</section>

<section class="bOffice">
    <?php if(isset($_SESSION) && empty($_SESSION)): ?>
        <p>La connexion est obligatoire ici, veuillez vous connectez en tant qu'Administrateur du site en cliquant sur le bouton "Connexion" de cette page.</p>
    <?php endif; ?>
        <img src="../public/img/AClostlegacy.jpg" class="backHome" alt="Image Assassin's Creed">
        <img src="../public/img/steinsg.jpg" class="backHome" alt="Image steins gate">
        <img src="../public/img/soulhackers.jpg" class="backHome" alt="Image Soul Hackers">
</section>