
    <div>
        <p>Il y a <?= $numberOfGames ?> résultat(s) correspondant à cette recherche.</p>
    </div>
    
    <section class="games">
        <?php foreach($games as $game): ?>
        	<article class="game" id="game">
        	    <div class="image">
        	        <img src="../public/img/<?= htmlspecialchars($game["image"]) ?>" class="jaquette" alt="image">
        		</div>
        		<a href="index.php?road=displayGameTops&id=<?= htmlspecialchars($game['id_game']) ?>" title="dirige sur la page du jeu et tous ses commentaires"><h4><?= htmlspecialchars($game['jeux']) ?></h4></a>
        		<span><?= nl2br(htmlspecialchars($game['descriptif'])) ?></span>
        		<p>Type de Jeu : <?= htmlspecialchars($game['typeofgame']) ?></p>
        		<p>Multiplayers en local : <?= htmlspecialchars($game['multiplayerslocal']) ?></p>
        		<p>Online : <?= htmlspecialchars($game['online']) ?></p>
        		<p>Prix : ~ <?= htmlspecialchars($game['price']) ?> euros</p>
        	</article>
        <?php endforeach; ?>
    </section>
     