
<h1>Modifier un compte utilisateur !</h1>


<div class="formRegister">
    <form action="index.php?road=updateUser" method="POST">
        <input type="hidden" name="id" value="<?= $data['id'] ?>">
        
        <legend>Modification de l'utilisateur : <?= htmlspecialchars($data['username']) ?></legend>
        
        <?php require_once('_errors.phtml');?>
        <?php require_once('_valids.phtml');?>

        <label for="username">Entrez votre nom d'utilisateur</label>
        <input type="text" id="username" value="<?= $data['username'] ?>" name="username" size="30">
    
        <label for="email">Entrez votre email</label>
        <input type="email" id="email" value="<?= $data['email'] ?>" name="email" size="30">
    
        <label for="password">Choisissez un mot de passe</label>
        <div class="pass"><input type="password" value="<?= $data['password'] ?>" name="password" id="password" size="30"><i id="eye" class="fa-regular fa-eye-slash"></i></div>
    
        <label for="birthday">Entrez votre date de naissance</label>
        <input type="date" id="birthday" value="<?= $data['birthday'] ?>" name="birthday">
        
        <label for="role">Le role de cet utilisateur :</label>
        <select name="role" class="role" id="role">
            <option value="vide">Role</option>
            <?php foreach($roles as $role): ?>
                <option value="<?= htmlspecialchars($role['role']) ?>"><?= htmlspecialchars($role['role']) ?></option>
            <?php endforeach; ?>
        </select>
        <input type="submit" value="Valider"/>
    </form>
</div>