
<nav class="bloc nav">
    <ul class="miniNav">
        <li><a href="index.php?road=games" title="affiche un CRUD des jeux en Bdd sous forme de tableau">Games Array</a></li>
        <li><a href="index.php?road=usersArray" title="affiche un CRUD des utilisateurs en Bdd sous forme de tableau">Users Array</a></li>
    </ul>
</nav> 

<h2>Utilisateurs inscrits sur le site GoodVGames</h2>

<p>Nombre d'inscrits : <?= htmlspecialchars($numberOfUsers) ?></p>

    <?php require_once('_errors.phtml');?>
    <?php require_once('_valids.phtml');?>
    
<button class="add"><a href="index.php?road=formUsers" title="affiche un formulaire pour l'ajout d'un utilisateur en Bdd">Ajouter un utilisateur</a></button>

<section class="games">
    <?php foreach($users as $user): ?>
    	<article class="game">
    		<span>Nom d'utilisateur : <a href="?road=displayTopsUser&id=<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['username']) ?></a></span>
            <p>Email : <?= htmlspecialchars($user['email']) ?></p>
    		<p>Rôle : <?= htmlspecialchars($user['role']) ?></p>
    		<button class="update"><a href="?road=updateUser&id=<?= htmlspecialchars($user['id']) ?>" title="affiche un formulaire pour modifier un utilisateur en Bdd">Modifier</a></button>
            <button class="del"><a onclick="delAlert()" href="?road=deleteUser&id=<?= htmlspecialchars($user['id']) ?>" class="delete" title="supprime un utilisateur en Bdd">Supprimer</a></button>
    	</article>
    <?php endforeach; ?>
</section>