
<div class="container footer">
    <p><?=  GVGCITATION  ?></p>  
    
    <div class="container reseaux">
		<a href="https://fr-fr.facebook.com/" target="_blank" title="S'ouvre dans un nouvel onglet vers la page Facebook"><img src="public/icons/facebook.png" alt="icon Facebook" class="icons" /></a>
		<a href="https://twitter.com/" target="_blank" title="S'ouvre dans un nouvel onglet vers le fil Twitter"><img src="public/icons/twitter.png" alt="icon Twitter" class="icons" /></a>
		<a href="https://www.twitch.tv/" target="_blank" title="S'ouvre dans un nouvel onglet vers le compte Twitch"><img src="public/icons/twitch.png" alt="icon Twitch" class="icons" /></a>
		<a href="https://discord.com/" target="_blank" title="S'ouvre dans un nouvel onglet vers le compte Discord"><img src="public/icons/discord.png" alt="icon Discord" class="icons" /></a>
    </div>
    <div class="container footer end">
        <a href="#" title="About">About</a>
        <a href="#" title="Contact">Contact</a>
        <a href="#" title="CGU">CGU</a>
    </div>
</div>
