
<h2>Les Jeux Vidéos jusqu'au Top</h2>
<section class="homefront">
    <article class="homegvg">
        <p>Créer votre compte sur le site et crée votre Top des jeux Vidéos qui sont présent dans la base de données.</p>
        <p>Vous pourrez y mettre vos notes, vos arguments, vos tests ou vos conseils sur vos jeux préférés.</p>
        <p>L'industrie du Jeu Vidéo est devenu un des leaders du divertissement et les possiblités qu'offrent ce support sont impréssionantes. Entre la Réalité Virtuelle, le jeu en réseaux, les applications avec interactions du smartphone, les différents styles de jeux trouveront toujours une manière d'innover et de surpendre le joueur. Son public est de plus en plus large et il y en a pour tout les goûts. N'hésitez plus, partagez votre avis et votre Top Video Games !</p>
        <div class="slider">
            <img src="public/img/609858.jpg" alt="imageDanganronpa" class="img_slider active" />
            <img src="public/img/922776.jpg" alt="chaosChildimage" class="img_slider" />
            <img src="public/img/922638.jpg" alt="persona4Gimage" class="img_slider" />
            <div class="back">
                <button><i class="fa-solid fa-left"><</i></button>
            </div>
            <div class="next">
                <button><i class="fa-solid fa-right">></i></button>
            </div>
        </div>
    </article>
</section>
