<h3>Connectez vous à votre compte utilisateur !</h3>


<div class="formRegister">
    <form action="index.php?road=connectUser" method="POST">
        
        <legend>Connexion :</legend>
        
        <?php require_once('_errors.phtml');?>
        <?php require_once('_valids.phtml');?>
    
        <label for="email">Entrez votre email</label>
        <input type="email" name="email" size="30">
    
        <label for="password">Mot de passe</label>
        <div class="pass">
            <input type="password" name="password" id="password" size="30" placeholder="6 caractères minimum">
            <i id="eye" class="fa-regular fa-eye-slash"></i>
        </div>
        <input type="submit" value="Valider"/>
    </form>
</div>