
<h3>Créer un compte utilisateur sur GoodVGames !</h3>

<div class="formRegister">
    <form action="index.php?road=addUser" method="POST">
        
        <legend>Inscription :</legend>
        
        <?php require_once('_errors.phtml');?>
        <?php require_once('_valids.phtml');?>

        <label for="username">Entrez votre nom d'utilisateur</label>
        <input type="text" name="username" size="30">
    
        <label for="email">Entrez votre email</label>
        <input type="email" name="email" size="30">
    
        <label for="password">Choisissez un mot de passe</label>
        <div class="pass"><input type="password" name="password" id="password" size="30" placeholder="6 caractères minimum"><i id="eye" class="fa-regular fa-eye-slash"></i></div>
    
        <label for="password_verify">Confirmez le mot de passe choisi</label>
        <div class="pass"><input type="password" name="password_verify" id="password_verify" size="30"><i id="eye2" class="fa-regular fa-eye-slash"></i></div>

        <label for="age">Entrez votre date de naissance</label>
        <input type="date" name="age">
    
        <input type="submit" value="Valider"/>
    </form>
</div>

